/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/renderer/index.html', './src/renderer/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        accent: {
          DEFAULT: 'rgb(var(--accent-rgb) / <alpha-value>)',
          hover: 'rgb(var(--accent-hover-rgb) / <alpha-value>)',
          active: 'rgb(var(--accent-active-rgb) / <alpha-value>)',
          soft: 'rgb(var(--accent-soft-rgb) / <alpha-value>)',
        },
        app: {
          bg: 'var(--app-bg)',
          'bg-login': 'var(--app-bg-login)',
          surface: 'var(--app-surface)',
          card: 'var(--app-card)',
          'surface-input': 'var(--app-surface-input)',
          border: 'var(--app-border)',
          'border-subtle': 'var(--app-border-subtle)',
          'border-strong': 'var(--app-border-strong)',
          text: 'var(--app-text)',
          muted: 'var(--app-text-muted)',
          placeholder: 'var(--app-placeholder)',
          'chat-bg': 'var(--app-chat-bg)',
          'chat-rail': 'var(--app-chat-rail)',
          'chat-sidebar': 'var(--app-chat-sidebar)',
          'chat-panel': 'var(--app-chat-panel)',
          'chat-hover': 'var(--app-chat-hover)',
          'chat-active': 'var(--app-chat-active)',
          elevated: 'var(--app-elevated)',
          inset: 'var(--app-inset)',
          'inset-active': 'var(--app-inset-active)',
          'avatar-fallback': 'var(--app-avatar-fallback)',
          'message-in': 'var(--app-message-in)',
          'message-out': 'var(--app-message-out)',
          'message-out-text': 'var(--app-message-out-text)',
          glass: 'var(--app-glass-bg)',
        },
        surface: {
          DEFAULT: '#1c1e27',
          input: '#121318',
        },
        border: {
          DEFAULT: 'var(--app-border)',
          input: 'var(--app-border)',
        },
        muted: '#9a9a9a',
        chat: {
          bg: 'var(--app-chat-bg)',
          rail: 'var(--app-chat-rail)',
          sidebar: 'var(--app-chat-sidebar)',
          panel: 'var(--app-chat-panel)',
          hover: 'var(--app-chat-hover)',
          active: 'var(--app-chat-active)',
        },
      },
      borderColor: {
        DEFAULT: 'var(--app-border)',
      },
      boxShadow: {
        app: '0 24px 48px var(--app-shadow)',
        glass: '0 8px 32px 0 var(--app-shadow)',
        'accent-glow': '0 0 20px -3px rgba(var(--accent-rgb) / 0.35)',
        composer: 'var(--app-composer-shadow)',
        'composer-focus': '0 16px 40px -4px var(--app-shadow), 0 0 0 1.5px rgba(var(--accent-rgb) / 0.5), 0 0 24px -2px rgba(var(--accent-rgb) / 0.25)',
      },
    },
  },
  plugins: [],
};
